[package]
name = "vehicle-pos-producer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { version = "0.28", features = ["cmake-build"] }
tokio = { version = "1.21.2", features = ["full"] }
